baseURL: "https://wiki.vrisingmods.com/"
title: "V Rising Mod Wiki"
description: "Information about mods for the game V Rising: How to build, debug, and publish your mods."
theme: "hugo-theme-relearn"

markup:
  goldmark:
    renderer:
      unsafe: true

ignoreLogs:
  - warning-goldmark-raw-html

permalinks:
  prefabs: "/prefabs/:filename/"

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

params:
  back_to_top: true
  back_to_top_text: "Back to top"
  search:
    adapter:
      identifier: lunr
  focus_shortcut_key: "k"
  enable_copy_code_button: true
  discordURL: "https://discord.gg/your-link"
  callouts:
    warning:
      title: Warning
      color: red
    grey-lt:
      title: Note
      color: grey-lt
    yellow:
      title: Note
      color: yellow
    green:
      title: Note
      color: green
menu:
  main:
    - identifier: developers
      name: For Developers
      url: /dev/
      weight: 10
    - parent: developers
      name: Development Setup
      url: /dev/development_setup/
      weight: 1
    - parent: developers
      name: Migration Guide
      url: /dev/migration_guide/
      weight: 2
    - identifier: users
      name: For Users
      url: /user/
      weight: 20
    - parent: users
      name: Mod Install
      url: /user/mod_install/
      weight: 1
    - parent: users
      name: Using Server Mods
      url: /user/using_server_mods/
      weight: 2
    - identifier: prefabs
      name: Prefabs
      url: /prefabs/
      weight: 30
    - parent: prefabs
      name: All
      url: /prefabs/all/
      weight: 1
    - parent: prefabs
      name: Castle
      url: /prefabs/castle/
      weight: 2

