baseURL: "https://mfoltz.github.io/"
title: "V Rising Mod Wiki"
description: "Information about mods for the game V Rising: How to build, debug, and publish your mods."
theme: "hugo-theme-relearn"

markup:
  goldmark:
    renderer:
      unsafe: true

ignoreLogs:
  - warning-goldmark-raw-html

permalinks:
  prefabs: "/prefabs/:filename/"

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

params:
  back_to_top: true
  back_to_top_text: "Back to top"
  themeVariant: vampire
  search:
    adapter:
      identifier: lunr
  focus_shortcut_key: "k"
  aux_links:
    "V Rising Thunderstore": "https://thunderstore.io/c/v-rising/"
  enable_copy_code_button: true
  callouts:
    warning:
      title: Warning
      color: red
    grey-lt:
      title: Note
      color: grey-lt
    yellow:
      title: Note
      color: yellow
    green:
      title: Note
      color: green
