name: Build and Deploy Jekyll to Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: [self-hosted, windows]

    steps:
      - uses: actions/checkout@v4

      - name: Ensure latest Bundler
        run: gem install bundler

      - uses: actions/cache@v4
        with:
          path: |
            _site
            .jekyll-metadata
          key: jekyll-incremental-${{ hashFileshashFiles('Gemfile.lock', '_config.yml') }}
          restore-keys: |
            jekyll-incremental-

      - name: Install dependencies
        run: bundle install

      - name: Build Site
        run: bundle exec jekyll build --incremental

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
