name: Build site
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec jekyll build
